### ISSUE TITLE
Auto starting last print after connecting to printer

### ISSUE THREAD

**Issue by jerryfromearth** [jneilliii/OctoPrint-Tasmota#149] opened 2021-04-30 08:12 UTC
Hi, 

Thank you for the great plugin!

I'm suspecting this issue (https://github.com/jneilliii/OctoPrint-Tasmota/issues/124) is coming back.
OctoPrint-Tasmota version: 1.0.3
OctoPrint version: 1.6.0

How to reproduce:
I usually do both "power on printer" and "connect" through Octoprint/OctoPrint-Tasmota WebUI, and then select which one I should print.
Sometimes after clicking "connect", printer would start printing the gcode that was successfully printed last time, again. So I have to immediately stop it.

How I upload gcode files (dunno if it matters):
I usually use "Send to Printer" without "start printing after upload" in SuperSlicer.

Here's the octoprint.log I got from the moment when I visited Octoprint UI:
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6403822/octoprint.log)

plugin_tasmota_debug.log didn't contain anything about this instance.

**Comment by jneilliii** [comment] 2021-04-30 15:19
Did you have debug logging enabled for the plugin? It would be good to see what the plugin logs. Also, can you test with the current release candidate to see if the issue persists? You can change the release channel in OctoPrint's software update settings.

**Comment by TheToxicant** [comment] 2021-05-02 13:41
I'm actually having this problem with another printer where I use this plug in to shut it down after its been idling for a while.

**Comment by jneilliii** [comment] 2021-05-02 14:06
> I'm actually having this problem with another printer where I use this plug in to shut it down after its been idling for a while.

Would be great to get debug logging enabled for you and more data on this. There has to be some workflow you are using that is bypassing the resets I have in place.

**Comment by TheToxicant** [comment] 2021-05-02 14:24
Not a problem I am waiting on some parts for the printer to show up today but I just turned debugging on and will let it power cycle in-between my next few print to let up build a log.

**Comment by jerryfromearth** [comment] 2021-05-03 12:00
Okay it happened again today with 1.0.4rc2 (I haven't got chance to upgrade to rc3 yet).

It started printing the previously finished print as soon as I powered on tasmota and connected to the printer (both done through octoprint UI).

One thing that matters might be that: before I did the things above, I used SuperSlicer to send a gcode to Octoprint (but asked it to not start printing immediately, since I had stuff to remove from the build plate). (Note that when the printer started printing after poweron&connect, it started printing a previously finished gcode, instead of this newly uploaded gcode).

Here's the tasmota debug log, and octoprint log
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6414614/plugin_tasmota_debug.log)
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6414635/octoprint.log)

**Comment by TheToxicant** [comment] 2021-05-08 14:02
Just finished a 102 our print here is a log file from that time frame.
[plugin_tasmota_debug.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6445945/plugin_tasmota_debug.log) 
[octoprint.log](https://github.com/jneilliii/OctoPrint-Tasmota/files/6445947/octoprint.log)

**Comment by devosthomas** [comment] 2021-05-20 17:46
I have the same issue now for the 2nd time. I started my printer an hour ago and prepared in another room my new print but wasn't able to send it because Cura asked to put it in the queue. To my big surprise it was printing my previous model again and it was almost finished :)

**Comment by jerryfromearth** [comment] 2021-06-21 07:17
This is still happening on the latest version (1.0.4rc4), but one thing I can add is that it only happens if I press "power on" button and allow octopi to connect to the printer (ender 5) automatically.
In other words, recently I have been manually clicking "Connect" immediately after pressing the "power on" red lightning button, and the issue hasn't been seen ever since I started to do that.

**Comment by jneilliii** [comment] 2021-06-21 13:54
Thanks for the hint Jerry, that helps with where I need to look. I still don't know why this is not clearing out on print completion like it should be.

**Comment by TheToxicant** [comment] 2021-06-21 13:58
> This is still happening on the latest version (1.0.4rc4), but one thing I can add is that it only happens if I press "power on" button and allow octopi to connect to the printer (ender 5) automatically.
> In other words, recently I have been manually clicking "Connect" immediately after pressing the "power on" red lightning button, and the issue hasn't been seen ever since I started to do that.

I can confirm it's still happening on mine as well but I wasn't sure why it would do sometimes and not others but after reading his comment that is what mine are doing for my Marlin printers.

**Comment by userix** [comment] 2021-09-02 08:20
I can confirm I have the same issue.  If I click on connect after the printer has turned off finishing a successful print, it will start immediately to print the previous successful print.

**Comment by jneilliii** [comment] 2021-09-04 06:31
I think I may have this issue resolved with the above commit. If everyone could test the 1.1.0rc1 release and verify that would be great. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. If you are already on that release channel, you should get an update notice once your local cache times out, or if you force a check.

**Comment by userix** [comment] 2021-09-06 08:48
Updated to RC 1.1.0rc2 and it's still having the same issue.  As soon as I connect, it automatically start the last print.

**Comment by devosthomas** [comment] 2021-09-06 08:50
Same with me, same behaviour.

**Comment by devosthomas** [comment] 2021-09-06 08:50
> Updated to RC 1.1.0rc2 and it's still having the same issue. As soon as I connect, it automatically start the last print.

Same with me

**Comment by jneilliii** [comment] 2021-09-06 15:27
I need more details then of your workflow and what is triggering the print start. I assume your already uploading direct from prusa slicer? Are you uploading files while a primer is ongoing, e.t.c. the more details you provide the better. Refresh of the log files wouldn't be a bad idea either.

**Comment by userix** [comment] 2021-09-07 18:31
> I need more details then of your workflow and what is triggering the print start. I assume your already uploading direct from prusa slicer? Are you uploading files while a print is ongoing, e.t.c. the more details you provide the better. Refresh of the log files wouldn't be a bad idea either.

I use Cura and send my prints directly to octoprint through Cura.  It starts printing like normal and then tasmota would turn off the printer after finishing successfully and the idle timeout passed.  Then once I connect manually through the octoprint web interface, it would turn on and immediately start the printing procedure for the part I just finished printing.

On another note, how does the auto power on upload feature work?  I try uploading new prints through cura when the printer is off and it doesn't automatically power on the printer again, it just says "printer is offline".  I was hoping the power on upload feature would work too.  Thank you!

**Comment by jneilliii** [comment] 2021-09-07 18:37
The OctoPrint connection plugin in Cura handles the powering on from the OctoPrint settings in printer management. It handles the process all on its own, telling the plugin to power on, uploading, waiting for PrintTimeGenius to finish analysis, and then starts print. If you want to utilize the new feature that was just implemented, if you check the Always option and Automatically power on option in settings under upload and not having it configured in Cura should act like it does from PrusaSlicer.

**Comment by drewmoseley** [comment] 2022-08-10 20:26
I've been troubleshooting a similar issue here with my setup; I assume it is the same root cause. I have a CR6-SE connected to OctoPI with the Tasmota plugin. I have Cura setup with the "Connect Octoprint" option and the "Turn On Printer" and "Start Print Job" settings (from Cura).

I wanted to experiment with PrusaSlicer and saw that I needed to enable "Upload Event Monitoring" and "On with upload" in the Octopi Tasmota plugin settings to allow PrusaSlicer to work.

With this collection of settings, when I print with PrusaSlicer, it all works as expected and I do not get the print retry on the next power-on. However, when I print with Cura, I do.

I am running plugin v1.1.2 and I see that this is targeted at the 1.1.3 release. Please let me know if there is any info I can provide or troubleshooting steps I can take to help.

**Comment by jneilliii** [comment] 2022-08-10 20:39
@drewmoseley have you tried this with the latest rc version? 

> If you want to utilize the new feature that was just implemented, if you check the Always option and Automatically power on option in settings under upload and not having it configured in Cura should act like it does from PrusaSlicer

**Comment by drewmoseley** [comment] 2022-08-11 13:43
OK. That does seem to work. Thanks.
To clarify in case others check here, I had to disable the power options in Cura as well as "Start print job after uploading" and "Select print job after uploading". Then in the Octoprint plugin settings I had to enable 'Upload Event Monitoring", "Include uploads via web interface" and "Automatically start print after on".

**Closed** 2024-06-08 18:06 UTC
Labels: bug
