### ISSUE TITLE
'On with Upload' not working

### ISSUE THREAD

**Issue by PoLoMoTo** [jneilliii/OctoPrint-Tasmota#115] opened 2021-01-02 06:02 UTC
Power is not turned on when a file is uploaded to OctoPrint.  Turns off on idle and on/off with navbar button without issue.  I do have 'Upload Event Monitoring' enabled.  Not sure what would other info would be good to include here.

**Comment by jneilliii** [comment] 2021-01-02 06:56
The option is not technically described correctly. It's for use with PrusaSlicer/SuperSlicer/Slic3r send to octoprint with the option to automatically start the print. Cura has other alternatives using the OctoPrint Connection Plugin and has it's own settings for automatically powering on.

**Comment by PoLoMoTo** [comment] 2021-01-03 00:01
Ah that makes sense, sorry for the misunderstanding!

**Comment by Fredyy90** [comment] 2021-01-25 12:49
thank you for the explaination, i was also wondering why it didn't work as expected.
anyway "power on" on webinterface g-code upload would still be a nice function.

**Comment by jneilliii** [comment] 2021-01-25 16:18
Thanks @Fredyy90 that's why the issue is still open, I do plan on incorporating this eventually.

**Comment by jneilliii** [comment] 2021-09-04 06:32
I think I may have this issue resolved with the above commit. If you could test the 1.1.0rc1 release and verify that would be great. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted. If you are already on that release channel, you should get an update notice once your local cache times out, or if you force a check.

**Closed** 2021-09-04 22:34 UTC
Labels: enhancement, solved, documentation, support
